In [1]:
import sqlite3
from flask import Flask, render_template, jsonify, redirect
import random
import pandas as pd
import numpy as np
import random
app = Flask(__name__)
app.debug=True


br_db = sqlite3.connect('bitrate_db')
cursor = br_db.cursor()

In [ ]:
# def machine_learning():
#     angle_list = [random.randint(1, 90) for k in range(100)]
#     velocity_list = [random.uniform(0, 1) for k in range(100)]
#     moo=pd.DataFrame({'Angles' : angle_list,'Velocity' : velocity_list,}, columns=['Angles','Velocity', 'Result','MSE'])
#     moo.to_sql("Kikoken", br_db, if_exists="append")
#     moo.head(10)
 

In [2]:
# def no_machine_learning():
#     angle_list = [random.randint(1, 90) for k in range(100)]
#     velocity_list = [random.uniform(0, 1) for k in range(100)]


#=========create random values for angle and velocity
angle_list = [random.randint(1, 90) for k in range(1000)]
velocity_list = [random.uniform(0, 20) for k in range(1000)]
# success_failure=[random.randint(0, 1) for k in range(1000)]
moo=pd.DataFrame({'Angle' : angle_list,'Velocity' : velocity_list}, columns=['Angle','Velocity','MSE'])


In [3]:
moo.head()

Angle   Velocity  MSE
0     32  13.419337  NaN
1     34   4.486810  NaN
2     31   8.712218  NaN
3     75  11.060322  NaN
4     18   8.552987  NaN

In [4]:
#force a 'pattern' in the results columns
moo['Result'] = np.where((moo['Angle']>=80) & (moo['Velocity']<10), 1, 0)
moo.to_json('json.json', orient='records')

In [11]:
moo = moo.sort_values('Result', ascending=False)
moo

Angle   Velocity  MSE  Result
801     83   4.199998  NaN       1
558     84   1.372856  NaN       1
542     81   3.997006  NaN       1
237     88   8.867447  NaN       1
236     87   5.054457  NaN       1
168     82   4.074620  NaN       1
963     82   3.874630  NaN       1
296     88   6.070861  NaN       1
616     89   8.314296  NaN       1
835     90   0.299852  NaN       1
832     87   3.774382  NaN       1
468     81   3.776132  NaN       1
891     90   7.091466  NaN       1
305     85   1.738915  NaN       1
408     89   5.903697  NaN       1
898     90   1.523579  NaN       1
167     84   9.540343  NaN       1
605     83   3.468714  NaN       1
824     84   6.018899  NaN       1
317     80   6.043605  NaN       1
211     85   7.578282  NaN       1
69      86   8.953483  NaN       1
815     83   0.742539  NaN       1
442     85   6.570342  NaN       1
804     81   5.863160  NaN       1
590     86   4.228038  NaN       1
807     80   5.623897  NaN       1
79      82   5.674383  NaN       1
584     86   0.066899  NaN       1
194     81   9.784305  NaN       1
..     ...        ...  ...     ...
350     89  17.197381  NaN       0
349     68   7.777728  NaN       0
334     77  16.307282  NaN       0
322     42  17.978034  NaN       0
323     70   2.375315  NaN       0
324     10   6.173213  NaN       0
325     45   4.231386  NaN       0
326     36   4.272446  NaN       0
327     14   5.874861  NaN       0
328     44   1.690692  NaN       0
329     37   1.790507  NaN       0
330     32  10.675563  NaN       0
331     66  17.682280  NaN       0
332     44  17.422708  NaN       0
333     76  10.513609  NaN       0
335     59   1.698736  NaN       0
348     57  12.852743  NaN       0
336     22  14.587831  NaN       0
337     58   0.549947  NaN       0
338     58   6.352320  NaN       0
339     20   0.685541  NaN       0
340     19   9.888884  NaN       0
341     78   4.459593  NaN       0
342     24  18.654607  NaN       0
343     57   7.220309  NaN       0
344      3  16.204855  NaN       0
345     47   3.792700  NaN       0
346     50   4.031669  NaN       0
347     83  16.691754  NaN       0
999     33  13.653249  NaN       0

[1000 rows x 4 columns]

In [15]:
test=pd.read_json('json.json')
test['Result']
labels=test['Result'].values
data = test[['Angle','Velocity']].values

In [16]:
#machine learning model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, labels, random_state=1, stratify= labels)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
classifier.score(X_train, y_train)
classifier.score(X_test, y_test)




0.96399999999999997

In [17]:
classifier.predict([65, 30])

/Users/michaelcavellero/anaconda/envs/PythonData/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [18]:
classifier.predict([[12121, 23], [65, 30]])

array([1, 0])

In [19]:
newSimulation = [[12121, 23], [65, 30]]
    

In [20]:
success_guesses = classifier.predict([[12121, 23], [65, 30]])

In [21]:
newSimulation

[[12121, 23], [65, 30]]

In [22]:
success_guesses

array([1, 0])

In [23]:
for num in success_guesses:
    if (num == 1):
        print(num)
        print(newSimulation[num])

1
[65, 30]


In [24]:
for x in range(len(success_guesses)):
    if (success_guesses[x] == 1):
        print(success_guesses[x])
        print(newSimulation[x])

1
[12121, 23]


In [ ]:
# def drop_table():

cursor.execute('DROP TABLE Kikoken')