In [2]:
# Dependencies and Setup
import sqlite3
from flask import Flask, render_template, jsonify, redirect
import random
import pandas as pd
import numpy as np
import math


app = Flask(__name__)
app.debug=True

# Database Storage
br_db = sqlite3.connect('bitrate_db')
cursor = br_db.cursor()

In [3]:
math.pi

3.141592653589793

def projectile_motion_range(initial_velocity,gravity,angle,horizontal_range):
    """
    Parameters
    ==========
    initial_velocity : float
        initial_velocity of the projectile
    gravity : float
        gravity
    angle : float
    
    Results
    =======
    horizontal_range : float
        horizontal_range
    """
    import numpy as np.sin()
    horizontal_range = ((initial_velocity^2)(np.sin2(angle))/(gravity)
    return horizontal_range

def projectile_motion_time(initial_velocity,gravity,angle,maximum_height):
    """
    Parameters
    ==========
    initial_velocity : float
        initial_velocity of the projectile
    gravity : float
        gravity
    angle : float
    
    Results
    =======
    maximum_height : float
        Range
    """
    import numpy as np
    maximum_height = ((initial_velocity^2)(np.sin^2(angle))/(gravity)
    return maximum_height

def projectile_motion_height(initial_velocity,gravity,angle,time_of_flight):
    """
    Parameters
    ==========
    initial_velocity : float
        initial_velocity of the projectile
    gravity : float
    angle : float
    
    Results
    =======
    time_flight : float
        Range
    """
    
    import numpy as np
    time_of_flight = (2(initial_velocity)(np.sin(angle))/(gravity)
    return time_of_flight

def horizontal_velocity(Initial_Velocity, Initial_Angle):
    """
    Parameters
    ==========
    Initial_Velocity : float
        Horizontal Velocity of the projectile
    
    Results
    =======
    Horizontal Velocity : float
        Horizontal Velocity of the projectile
    """
    
    import numpy as np
    import math
    math.pi
    horizontal_velocity = (Initial_Velocity*2)[cos(Initial_Angle*/180)]
    return horizontal_velocity

def vertical_velocity(Initial_Velocity,Initial_Angle,vertical_velocity):
    """
    Parameters
    ==========
    Vertical Velocity : float
        Vertical Velocity of the projectile
    
    Results
    =======
    Vertical Velocity : float
        Vertical Velocity of the projectile    
    """    
    import numpy as np
    vertical_velocity = (Initial_Velocity*2)[sin()/180]
    return vertical_velocity

def free_fall_time(acceleration_due_to_gravity,vertical_velocity,free_fall_time):
    """
    Parameters
    ==========
    acceleration_due_to_gravity : float
    
    Results
    =======
    Free Fall time : float
        Free Fall time of the projectile
    """
    
    acceleration_due_to_gravity = 9.8
    free_fall_time = vertical_velocity/acceleration_due_to_gravity
    return free_fall_time

def total_time(Free_fall_time,Total time):
    """
    Parameters
    ==========
    Free_fall_time : float
    
    Results
    =======
    Total time : float
        total time of the projectile
    """
    
    total_time
    total_time = 2*free_fall_time
    return total_time

def Maximum_Height(vertical_velocity,Maximum_Height):
    """
    Parameters
    ==========
    maximum : float
    
    Results
    =======
    Maximum_Height = float
        Maximum of the projectile
    """
    
    Maximum_Height = (vertical_velocity*2)/(2*Acceleration_due_to_gravity)
    return Maximum_Height

def Range(Horizontal_Velocity,Total_time):
    """
    Parameters
    ==========
    maximum : float

    Results
    =======
    Range = float
        Range of the projectile 
    """
    
    Range = (Horizontal_Velocity*Total_Time)
    return Range 

In [4]:
values = [[3.0,4],[6.0,9],[10.0,15]]
last_values = [0,0]
last_velocity = 0
delta = 0.1  # Will need to play with this value.
terminal_velocity = None
for pos, time in values:
    velocity = (pos - last_values[0]) / (time - last_values[1])
    if abs(velocity - last_velocity) < delta:
        terminal_velocity = velocity
        break
    last_values = [pos, time]
    last_velocity = velocity
print ('Terminal Velocity:', terminal_velocity)

Terminal Velocity: 0.6666666666666666


In [5]:
#for pos, time in values:
#    velocity = (pos - last_values[0] / (time - last_values[1]))
#    if abs(velocity - last_velocity < delta:
#          terminal_velocity = velocity
#          break
#    last_values = []
#    last_velocity = velocity
#print ())

In [6]:
# Calculations
angle = [random.randint(1, 90) for k in range(1000)]
velocity = [random.randint(0, 100) for k in range(1000)]
velocity = np.array(velocity)
angle = np.array(angle)
gravity = 9.8
horizontal_velocity = velocity * (np.cos(angle*math.pi)/180)
vertical_velocity =  velocity * (np.sin(angle*math.pi)/180)
free_fall_time = (vertical_velocity/9.8)
total_time = (2*free_fall_time)
maximum_height = (2*vertical_velocity/(2*gravity))
#Range = (horizontal_velocity*total_time)

Range = ((velocity**2)*(np.sin(2*angle))/9.8)
# print(Range)


Range = ((velocity**2)*(np.sin(2*angle*3.14/180))/9.8)
print(Range)


[  3.42903487e+02   1.47984260e+02   6.16841072e+01   2.39066703e+01
   9.96204952e+01   9.22051052e+01   2.94311871e+02   9.58653679e+00
   4.96966067e+02   1.29573703e+02   6.49541437e+02   3.56454048e+01
   8.48195237e-02   5.52828631e+00   3.46031035e-01   1.69461534e+01
   1.97117863e+01   2.29398854e+00   7.57907158e+01   4.08045548e+01
   4.69293688e+02   3.74392583e+02   5.68113083e+01   6.80490702e+02
   1.32339662e+02   3.80529651e+02   5.99704281e+01   9.13371041e+01
   2.04968877e+02   6.89093742e+00   1.25592215e+02   1.23469349e+01
   6.15252179e+01   2.14374568e+00   1.61078207e+02   3.61874322e+01
   3.38874207e+02   1.75178212e+02   9.79864756e+01   1.85391660e+01
   6.90124086e+00   7.52496756e+01   3.01703463e+02   1.91865903e+02
   1.62858887e+00   1.25174607e+02   1.05935826e+01   1.95395687e+02
   3.55203969e+02   4.97254072e+02   1.01060038e-01   4.89034034e+02
   6.28996131e+02   1.64084769e+01   2.48313047e-02   2.97070199e+01
   5.70200518e+01   6.96074625e+02

In [7]:
# Creating the dataframe
moo=pd.DataFrame({'Angle': angle,
                  'Velocity': velocity,
                  'Horizontal Velocity': horizontal_velocity,
                  'Vertical Velocity': vertical_velocity,
                  'Free Fall Time': free_fall_time,
                  'Total Time': total_time,
                  'Maximum Height': maximum_height,
                  'Range': Range
                 },
#                columns=['Angle','Velocity','Gravity']
                )
# Data Munging

# Display the dataframe
moo.head(20)

Angle  Free Fall Time  Horizontal Velocity  Maximum Height       Range  \
0      15    2.505409e-16            -0.455556    2.505409e-16  342.903487   
1      85    3.537230e-16            -0.505556    3.537230e-16  147.984260   
2       7    2.429855e-17            -0.277778    2.429855e-17   61.684107   
3      87    7.571688e-16            -0.261111    7.571688e-16   23.906670   
4       5    2.603416e-17            -0.416667    2.603416e-17   99.620495   
5       3    1.936941e-17            -0.516667    1.936941e-17   92.205105   
6      20   -9.302873e-17             0.372222   -9.302873e-17  294.311871   
7      35    4.443865e-17            -0.055556    4.443865e-17    9.586537   
8      35    3.199583e-16            -0.400000    3.199583e-16  496.966067   
9      56   -1.438474e-16             0.205556   -1.438474e-16  129.573703   
10     48   -2.665898e-16             0.444444   -2.665898e-16  649.541437   
11      6   -1.707841e-17             0.227778   -1.707841e-17   35.645405   
12      6   -8.330931e-19             0.011111   -8.330931e-19    0.084820   
13     21   -5.004874e-18            -0.050000   -5.004874e-18    5.528286   
14     29   -1.403584e-21            -0.011111   -1.403584e-21    0.346031   
15      1    4.790285e-18            -0.383333    4.790285e-18   16.946153   
16      3    8.955750e-18            -0.238889    8.955750e-18   19.711786   
17     58    7.017921e-21             0.027778    7.017921e-21    2.293989   
18     20   -4.720861e-17             0.188889   -4.720861e-17   75.790716   
19      5    1.666186e-17            -0.266667    1.666186e-17   40.804555   

      Total Time  Velocity  Vertical Velocity  
0   5.010817e-16        82       2.455300e-15  
1   7.074460e-16        91       3.466485e-15  
2   4.859710e-17        50       2.381258e-16  
3   1.514338e-15        47       7.420254e-15  
4   5.206832e-17        75       2.551347e-16  
5   3.873883e-17        93       1.898203e-16  
6  -1.860575e-16        67      -9.116815e-16  
7   8.887730e-17        10       4.354987e-16  
8   6.399165e-16        72       3.135591e-15  
9  -2.876948e-16        37      -1.409705e-15  
10 -5.331796e-16        80      -2.612580e-15  
11 -3.415682e-17        41      -1.673684e-16  
12 -1.666186e-18         2      -8.164312e-18  
13 -1.000975e-17         9      -4.904777e-17  
14 -2.807168e-21         2      -1.375513e-20  
15  9.580570e-18        69       4.694479e-17  
16  1.791150e-17        43       8.776635e-17  
17  1.403584e-20         5       6.877563e-20  
18 -9.441721e-17        34      -4.626443e-16  
19  3.332372e-17        48       1.632862e-16

In [8]:
np.array(velocity) * 3.14

array([ 257.48,  285.74,  157.  ,  147.58,  235.5 ,  292.02,  210.38,
         31.4 ,  226.08,  116.18,  251.2 ,  128.74,    6.28,   28.26,
          6.28,  216.66,  135.02,   15.7 ,  106.76,  150.72,  213.52,
        298.3 ,  229.22,  307.72,  248.06,  194.68,  204.1 ,  178.98,
        163.28,  138.16,  166.42,   34.54,  100.48,   75.36,  182.12,
        141.3 ,  263.76,  141.3 ,  166.42,   43.96,   34.54,  100.48,
        292.02,  182.12,   12.56,  222.94,   43.96,  207.24,  185.26,
        226.08,    3.14,  244.92,  301.44,  106.76,    3.14,   56.52,
         75.36,  292.02,  298.3 ,  122.46,  276.32,  191.54,  125.6 ,
        194.68,   18.84,  292.02,  229.22,  298.3 ,  191.54,  238.64,
        304.58,  235.5 ,   28.26,  298.3 ,  188.4 ,  213.52,  298.3 ,
         72.22,  216.66,  266.9 ,   31.4 ,  304.58,  178.98,   78.5 ,
         34.54,   50.24,  182.12,  185.26,  109.9 ,  119.32,   31.4 ,
        304.58,  191.54,  288.88,  125.6 ,   50.24,  288.88,   69.08,
        131.88,  251

In [13]:
# Force a 'pattern' in the results columns
moo['Result'] = np.where((moo['Range']>=300) & (moo['Range']<=310), 1, 0)
moo.to_json('json.json', orient='records')

In [14]:
# Sort Values
moo = moo.sort_values('Result', ascending=False)
moo.head()

Angle  Free Fall Time  Horizontal Velocity  Maximum Height       Range  \
991     61    1.310319e-16            -0.327778    1.310319e-16  301.433157   
63      65    6.543863e-16            -0.344444    6.543863e-16  300.766838   
806     27    2.371966e-16            -0.338889    2.371966e-16  307.072131   
971     76   -1.066584e-15             0.444444   -1.066584e-15  307.368895   
42      10   -6.456471e-17             0.516667   -6.456471e-17  301.703463   

       Total Time  Velocity  Vertical Velocity  Result  
991  2.620638e-16        59       1.284113e-15       1  
63   1.308773e-15        62       6.412986e-15       1  
806  4.743933e-16        61       2.324527e-15       1  
971 -2.133167e-15        80      -1.045252e-14       1  
42  -1.291294e-16        93      -6.327342e-16       1

In [9]:
# Jsonify the Output
Test = pd.read_json('json.json')
Test['Result']
Labels = Test['Result'].values
Data = test[['Angle','Velocity']].values

In [10]:
# Machine learning model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, labels, random_state=1, stratify= labels)

# Model for LogisticRegression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
classifier.score(X_train, y_train)
classifier.score(X_test, y_test)

0.96399999999999997

In [11]:
# 
classifier.predict([65, 30])

C:\Users\Abe\Anaconda2\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0], dtype=int64)

In [12]:
#
classifier.predict([[12121, 23], [65, 30]])

array([1, 0], dtype=int64)

In [13]:
#
newSimulation = [[12121, 23], [65, 30]]

In [14]:
#
success_guesses = classifier.predict([[12121, 23], [65, 30]])

In [15]:
#
newSimulation

[[12121, 23], [65, 30]]

In [16]:
#
success_guesses

array([1, 0], dtype=int64)

In [17]:
#
for num in success_guesses:
    if (num == 1):
        print(num)
        print(newSimulation[num])

1
[65, 30]


In [22]:
# 
for x in range(len(success_guesses)):
    if (success_guesses[x] == 1):
        print(success_guesses[x])
        print(newSimulation[x])

NameError: name 'success_guesses' is not defined

In [19]:
#API Infrastructure
@app.route("/")
def home():
    return ("Hi!")

In [21]:
#API Infrastructure
@app.route("/practice", methods=["GET", "POST"])
def practice():

    # Initial Data
    practiceData = []
    
# Convert to DataFrame
practiceDF = pd.DataFrame(practiceData)

# Separate "Labels" and "Data"
labels = practiceDF["Success_Failure"].values
data = practiceDF[["Angle", "Velocity"]].values

# Create a Logistic Model 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, labels, random_state=1, stratify=labels)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

classifier.fit(X_train, y_train)

# Score the Model
train_score = classifier.score(X_train, y_train)
test_score = classifier.score(X_test, y_test)

# Pickle 
pickle.dump(classifier, open("Classifier.sav", 'wb'))

# Return the Data
return(str(train_score))

# Route for Filtering JSONs
@app.route("/replay", methods=["GET", "POST"])
def replay(): 

    # Replay Data
    replayData = []

NameError: name 'practiceData' is not defined

In [ ]:
#def drop_table():
cursor.execute('DROP TABLE Kikoken')

In [ ]:
# Filtered List
filteredData = []

# Reload the classifier
classifier = pickle.load(open("Classifier.sav", 'rb'))

# Filter it down using the Classifier
for x in range(len(replayData)):

print(replayData[x])
if(classifier.predict([replayData[x]["Angle"], replayData[x]["Velocity"]]) == 1):
    filteredData.append(replayData[x])

print(len(replayData))
print(len(filteredData))

# Display only filtered Data
return(jsonify(filteredData))

#################################################
# Flask Boilerplate
#################################################
if __name__ == '__main__':
    app.run(debug=True)